apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cloudshop
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["backend"]
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: backend
          image: hashicorp/http-echo:1.0
          args:
            - "-listen=:8080"
            - "-text=CloudShop API v1"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
