apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-bind-read-cm-secrets
  namespace: cloudshop
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: cloudshop
roleRef:
  kind: Role
  name: backend-read-cm-secrets
  apiGroup: rbac.authorization.k8s.io
